//
// Created by Razvan on 1/28/2024.
//

#ifndef LAB8_BLINN_PHONG_CONSTANTS_H
#define LAB8_BLINN_PHONG_CONSTANTS_H

#define NR_OF_SOLID_OBJECTS 3
#define NR_OF_POINT_LIGHTS 2


#endif //LAB8_BLINN_PHONG_CONSTANTS_H
